### ISSUE TITLE
tvnamer stalls after detecting series name

### ISSUE THREAD

**Issue by thagler** [dbr/tvnamer#109] opened 2015-03-20 02:37 UTC
tvnamer began stalling on me today after it detects a file's series name. It now does this on all files, regardless of filename. After waiting, I CTRL+C and get a traceback, but nothing that indicates what I can do fix it.

I haven't made any recent config.json changes. It was working fine this morning, and now it's consistently stalling on all files. I can curl thetvdb.com from the same machine.

The complete output (including where I finally give up and hit CTRL+C) can be found at this gist: https://gist.github.com/thagler/45eef4682b28352bc543

I don't know how to debug this any further, so please let me know if there are useful logs, etc.

**Comment by dbr** [comment] 2015-03-22 13:23
Running with `tvnamer --verbose` might give some useful indication of what was wrong

Chances are the delays are caused by thetvdb.com being down or slow - is this still happening?

**Comment by thagler** [comment] 2015-03-22 16:02
Using --verbose and leaving it running, it looks like there were 10 minute gaps between requesting and receiving data from thetvdb, as seen in this gist: https://gist.github.com/thagler/5c59461ffb36bd6ac02b

However, this morning, everything seems back to normal. A complete rename operation took ~4s.

**Comment by dbr** [comment] 2015-03-29 05:09
Hm, must have just been temporary slowness with thetvdb's servers. Closing

**Closed by dbr** 2015-03-29 05:09 UTC
