### ISSUE TITLE
Marvel's Agents of Shield

### ISSUE THREAD

**Issue by AlbertoAIG** [dbr/tvnamer#145] opened 2018-04-18 05:57 UTC
Marvel's Agent of Shield is not rename without human intervention.
Tvnamer show: 

Processing file: Marvels.Agents.of.S.H.I.E.L.D.S05E17.720p.HDTV.x264-AVS[eztv].mkv
# Detected series: Marvels Agents of S H I E L D (season: 5, episode: 17)
Skipping file due to error: Show Marvels Agents of S H I E L D not found on www.thetvdb.com

But with human intervention:

# Processing file: Marvels.Agents.of.S.H.I.E.L.D.S05E17.720p.HDTV.x264-AVS[eztv].mkv.mkv
# Detected series: Marvels Agents of S H I E L D (season: 5, episode: 17)
ShowNotFound(u'Show Marvels Agents of S H I E L D not found on www.thetvdb.com',)
####################
Old filename: Marvels.Agents.of.S.H.I.E.L.D.S05E17.720p.HDTV.x264-AVS[eztv].mkv.mkv
New filename: Marvels Agents of S H I E L D 5x17.mkv
Rename?
([y]/n/a/q) y

**Comment by internetpopular** [comment] 2018-04-27 20:39
The issue is the removal of periods. Add these replacements to your .tvnamer.json file.

`"input_series_replacements": {"Marvel's Agents of S H I E L D": "Marvel's Agents of S.H.I.E.L.D.", "Marvels Agents of S H I E L D": "Marvel's Agents of S.H.I.E.L.D."} ,`

**Comment by aidanjt** [comment] 2018-05-14 10:40
And if you're using the move_files_* stuff and you have Windows clients browsing/copying from your destination directory, don't forget to have a fullpath_replacements, otherwise the directory name will get mangled by Samba, since Windows is such a precious princess about directories that end in a dot:

```json
"move_files_fullpath_replacements": [ { "is_regex": true, "match": "Marvel's Agents of S.H.I.E.L.D./", "replacement": "Marvel's Agents of S.H.I.E.L.D/" } ],
```

About the series replacement, I use this myself:
```json
"input_series_replacements": { "Marvel*s Agents of S*": 263365 },
```
The number is the series id of the show on thetvdb.

**Comment by dbr** [comment] 2018-08-25 04:00
Yep, thanks both - the `input_series_replacements` is the best way to deal with this for now as far as I'm aware. Closing

**Closed by dbr** 2018-08-25 04:00 UTC
